---
- hosts: all
  gather_facts: false
  tasks:

  - name: Check apt-ting
    shell: "apt list --upgradable 2>/dev/null | tail -n +2  | wc -l"
    register: updates
    ignore_errors: true

  - name: Number of updates available
    debug:
        msg: "Pending APT updates: {{ updates.stdout  }}"
