---
## Ansible Playbook to set up telegraf agent for influx
- hosts: all
  gather_facts: false
  become: true
  tasks:

    - name: Check if filebeat installed
      command: test -f /etc/filebeat/filebeat.yml
      register: fb_exists
      failed_when: false

    - name: Start filebeat
      service:
        name: filebeat
        state: started
      when: fb_exists.rc == 0

    - name: Start logstash
      service:
        name: logstash
        state: started
      when: fb_exists.rc == 0
