---
####  Ansible Playbook to set up telegraf agent for influx

# Agent, common
#- hosts: all
#  tasks:
#    - include_role:
#        name: telegraf

#Then separate hosts task lists for inputs, depending on include_role
- hosts: mysql
  tasks:
    - include_role:
        name: telegraf
        tasks_from: input_mysql

- hosts: docker
  tasks:
    - include_role:
        name: telegraf
        tasks_from: input_docker
