---
####  Ansible Playbook to set up telegraf agent for influx
- hosts: build  #Change to all when things run as they should.
  tasks:

    - include_role:
        name: telegraf
      when: false #Disable temporarily

    - include_role:
        name: telegraf
        tasks_from: input_mysql
      when: role == mysql

    - include_role:
        name: telegraf
        tasks_from: input_docker
      when: role == docker
