---
- hosts: mysql_source
  gather_facts: false
  become: true
  tasks:

    - name: Dump data locally on remote
      shell: mysqldump -A --add-drop-database | gzip > /var/lib/mysql/dumpall.sql)

    - name: Copy dump to localhost
      fetch:
        src: /var/lib/mysql/dumpall.sql
        dest: /tmp
        flat: yes

    - name: Remove dump from mysql-source
      file:
        path: /var/lib/mysql/dumpall.sql
        state: absent

- hosts: mysql_target
  gather_facts: false
  become: true
  tasks:
    - name: Copy now local dump to mysql-target
      copy:
        src: /tmp/dumpall.sql
        dest: /var/lib/mysql/dumpall.sql

    - name: Remove dump from localhost
      file:
        path: /tmp/dumpall.sql
        state: absent
      connection: local

    #- name: Import databasedump on mysql-target
    #  shell: mysql < /tmp/dumpall.sql

    - name: Remove dump from mysql-target
      file:
        path: /tmp/dumpall.sql
        state: absent
