---
## Ansible Playbook to set up telegraf agent for influx
- hosts: all
  gather_facts: false
  become: true
  tasks:

    - name: Remove logstash cycle cron job
      file:
        path: /etc/cron.daily/logstash-cycle
        state: absent
