---
- hosts: all
  gather_facts: false
  become: true
  tasks:

    - name: Slack notification - start
      become: false
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Ansible-run patching started on {{ inventory_hostname }}"
        color: warning

    - name: Run apt update
      apt:
        name: '*'
        state: latest
        #update_cache: true
        autoremove: true
        force_apt_get: true
      tags:
        - patch

    - name: Slack notification - finish
      become: false
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Ansible-run finished on {{ inventory_hostname }}"
        color: good
