---
- name: Add telegraf to docker group
  user:
    name: telegraf
    groups: docker
  notify: restart telegraf

- name: Set up docker input
  copy:
    src: input_docker.conf
    dest: /etc/telegraf/telegraf.d/input_docker.conf
    owner: telegraf
    group: telegraf
    mode: 0440
  notify: restart telegraf
